### ISSUE TITLE
[BUG] place page not loading on staging

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#446]
http://staging.datacommons.org/place?dcid=country%2FIND (https://screenshot.googleplex.com/6k7uWaZumDggoNd)

I've tried a few hard refreshes. While this could've been happening from before, I noticed this after rolling out a new data release to staging. The corresponding Browser page shows up fine.

**Comment by pradh** [comment]
From error logs, http://staging.datacommons.org/api/chart/data/geoId/0649670 fails with:

 textPayload: "Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/env/lib/python3.6/site-packages/flask_caching/__init__.py", line 907, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/vmagent/app/routes/api/chart.py", line 229, in config
    chart_config = build_config(raw_config)
  File "/home/vmagent/app/routes/api/chart.py", line 200, in build_config
    category, _ = config['category']
KeyError: 'category'

**Comment by pradh** [comment]
https://github.com/datacommonsorg/website/blob/master/server/routes/api/chart.py#L201

Deleting the 'category' there probably removes it from the global static current_app.config['CHART_CONFIG']. Should perhaps do a full copy before that.

**Comment by shifucun** [comment]
Thanks for the debugging!
